### ISSUE TITLE
Allow space between the avy character and the string

### ISSUE THREAD

**Issue by waymondo** [clemera/frog-menu#1]
This package is great. I started re-writing [`ace-jump-buffer`](https://github.com/waymondo/ace-jump-buffer) with it and it is allowing for more flexibility than being restricted to using `bs`.

One nitpick that I have though is that I wish there was a space between the avy character and the string in the posframe/side-window. I think it would improve the readability of the string options on quick glances at these transient popups. If you don't want this to be the default behavior, it would be great if this was an option.

Here's the `frog-menu` driven buffer list:
https://cl.ly/a6cfcb90625c

vs the `ace-jump-buffer`'s `bs` list:
https://cl.ly/a0eb06af2810

**Comment by clemera** [comment]
Good idea, I added the option `frog-menu-avy-padding`, please give it a try.

**Comment by waymondo** [comment]
very nice, thank you!

**Comment by clemera** [comment]
I restricted it to allow only one space and not an arbitrary padding because that broke the grid and I wanted to keep it simple for now. In the future the variable may change to accept any string as padding.

**Comment by waymondo** [comment]
Hi @clemera, I just pushed my first version of `frog-jump-buffer` if you are curious. Thanks for this package, it made implementing it much easier and cleaner.

https://github.com/waymondo/frog-jump-buffer

**Comment by clemera** [comment]
This looks great, I will check this out tomorrow!
