### ISSUE TITLE
flyspell-correct example cannot run actions

### ISSUE THREAD

**Issue by travitch** [clemera/frog-menu#4]
I'm trying the flyspell-correct example from the README in GUI emacs (X11/GTK if it matters), and actions don't seem to be working.  I can select corrections just fine, but selecting any of the actions always triggers the call to error (i.e., `frog-menu-read` returns `nil` if I trigger an action).

Any suggestions on where I should start looking?

**Comment by clemera** [comment]
Hi,

What if you try a minimal example using a menu like:

    (frog-menu-read "" nil '(("C-s" "save" save) ("C-k" "kill" kill)))

Which version of avy are you using?

**Comment by travitch** [comment]
Thanks - the minimal example worked as expected (save or kill echoed to the minibuffer).  I'm using the latest master of avy apparently (hash 85b5d574cdc4755b17ca549314774e15565f3e86)

**Comment by clemera** [comment]
Ok, thanks I can reproduce it now, I will look into that tomorrow.

**Comment by travitch** [comment]
Thanks!  Thanks for the package, by the way.  It is a perfect interface for this sort of thing.

**Comment by clemera** [comment]
Great to hear! Should be fixed, now.

**Comment by travitch** [comment]
Works great, thanks!

**Comment by clemera** [comment]
You are welcome!
