### ISSUE TITLE
Debugger entered--Lisp error: (void-function string-empty-p)

### ISSUE THREAD

**Issue by cyrus-and** [clemera/frog-menu#6]
I guess you need `(require 'subr-x)` somewhere in your `frog-menu.el` file.

**Comment by clemera** [comment]
Thanks fixed by f7a7abf412c4213e65edcfe24283d3e50903d429

**Comment by cyrus-and** [comment]
I don't get why it's wrapped in a `eval-when-compile` form though.

**Comment by clemera** [comment]
The functions used from `subr-x` are defined inline. Like with macros the compiled files contain the expanded code definitions and you shouldn't require the library at run-time because it's not needed anymore.

**Comment by cyrus-and** [comment]
I see, thanks for the explanation!

**Comment by clemera** [comment]
You are welcome!
