### ISSUE TITLE
Support all collection formats of completing-read

### ISSUE THREAD

**Issue by noctuid** [clemera/frog-menu#8]
`frog-menu-completing-read-function` / `frog-menu-read` do not work if passed a list of symbols.

**Comment by clemera** [comment]
Thank you! In my defense it's mentioned in the docstring. But I think I should just  add support for all other formats as well.

**Comment by clemera** [comment]
So probably I should add a threshold for the maximum of items. I don't think one would like to complete a hash table with frog menu :smile:

**Comment by clemera** [comment]
I have added support for all collection types of `completing-read` to `frog-menu-completing-read-function`.

**Comment by clemera** [comment]
Should work now
